version: '3.3'

# networks
# create a network 'guacamole_net' in mode 'bridged'
networks:
  guacamole_net:
    driver: bridge
# services
services:
  # nginx
  nginx:
    image: docker.io/library/nginx:stable-alpine
    restart: always
    logging:
      driver: journald
    networks:
      - guacamole_net
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - guacamole
  # guacd
  guacd:
    container_name: guacamole_backend
    image: kkpkishan/guacd:1.5.0-1-x86_64
    networks:
      guacamole_net:
    restart: always
    logging:
      driver: journald
    volumes:
    - ./recordings:/opt/guacamole/recording:rw


  # mysql
  mysql:
    container_name: guacamole_database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
    image: docker.io/library/mariadb:10.5
    networks:
      guacamole_net:
    restart: always
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/mysql:rw
    
  # guacamole
  guacamole:
    container_name: guacamole_frontend
    depends_on:
    - guacd
    - mysql
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      GUACAMOLE_HOME: /etc/guacamole
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_HOSTNAME: '${MYSQL_HOSTNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
    image: kkpkishan/guacamole:1.5.0-1-x86_64
    links:
    - guacd
    networks:
      - guacamole_net
    restart: always
    logging:
      driver: journald
    volumes:
    - ./guacamole/etc:/etc/guacamole:ro
    - ./recordings:/opt/guacamole/recording:rw
